builds:
  - binary: wsgate-server
    goos:
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: kazeburo
    name: wsgate-server
